# Generated by Django 3.1.7 on 2021-03-25 03:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cybercomplaint',
            name='id',
        ),
        migrations.AddField(
            model_name='cybercomplaint',
            name='email',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portal.email', unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CyberComplaintID',
        ),
    ]
